miner.setEtherbase(eth.accounts[4]);
console.log('coinbase: ', eth.coinbase);
var bal1=eth.getBalance(eth.coinbase);
var bal2=eth.getBalance(eth.accounts[5]);
var ch1=web3.fromWei(bal2,"ether");
console.log('The Sender balance in ether: ', web3.fromWei(bal1,"ether"));
console.log('The Receiver balance in ether: ', ch1);
console.log('Tranaction Count: ', eth.getTransactionCount(eth.coinbase));
var t=eth.sendTransaction({from:eth.coinbase, to:eth.accounts[5], value:1110000000000000000});
console.log('TransactionHash: ',t);
console.log('...mining start');
miner.start(1);admin.sleepBlocks(1);miner.stop();
console.log('mining done...');
var bal1new=eth.getBalance(eth.coinbase);
var bal2new=eth.getBalance(eth.accounts[5]);
var ch2=web3.fromWei(bal2new,"ether");
console.log('- New Sender balance in ether: ', web3.fromWei(bal1new,"ether"));
console.log('- New Receiver balance in ether: ', ch2);
console.log('- The change of Receiver in ether: ', ch2-ch1);
console.log('block number: ', eth.blockNumber);
