miner.setEtherbase(eth.accounts[4]);
console.log('coinbase: ', eth.coinbase);
var bal1=eth.getBalance(eth.coinbase);
var bal2=eth.getBalance(eth.accounts[5]);
console.log('The Sender balance in ether: ', web3.fromWei(bal1,"ether"));
console.log('The Receiver balance in ether: ', web3.fromWei(bal2,"ether"));
console.log('The Median gasPrice: ', eth.gasPrice);
console.log('block number: ', eth.blockNumber);
console.log('Tranaction Count: ', eth.getTransactionCount(eth.coinbase));
eth.sendTransaction({from:eth.coinbase, to:eth.accounts[5],value:1110000000000000000});
console.log('...mining start');
miner.start(1);admin.sleepBlocks(1);miner.stop();
console.log('mining done...');
var bal1new=eth.getBalance(eth.coinbase);
var bal2new=eth.getBalance(eth.accounts[5]);
console.log('- New Sender balance in ether: ', web3.fromWei(bal1new,"ether"));
console.log('- New Receiver balance in ether: ', web3.fromWei(bal2new,"ether"));
console.log('- The Block number: ', eth.blockNumber);
console.log('- Tranaction count: ', eth.getTransactionCount(eth.coinbase));
